In [61]:
import pandas as pd
import os.path

In [56]:
data = pd.read_csv("/home/harshit/geography/bse50.csv")
data.sort_values(by="HQ")
hqstates = set(data["HQ"])

In [50]:
for i in hqstates:
    df=pd.DataFrame(columns=["Company"])
    for index, j in data.iterrows():
        if(i==j["HQ"]): 
            m= pd.DataFrame([[j["Security Name"]]],columns=["Company"])
            df=df.append(m,ignore_index=True)
    df.to_csv("/home/harshit/geography/hqportfolios/"+i+".csv",index=False)

In [65]:
path ="/home/harshit/geography/hqportfolios/"
comp_path = "/home/harshit/geography/score_state/"
for i in hqstates:
    df = pd.read_csv(path+i+".csv")
    for j in df["Company"]:
        if(os.path.isfile(comp_path+j+".pdf.csv")==True):
            rem = pd.read_csv(comp_path+j+".pdf.csv")
            rem = rem

In [66]:
rem

                          State  count
0                         DELHI     58
1                       GUJARAT     29
2                       HARYANA     21
3                           GOA     12
4                     KARNATAKA      1
5                 UTTAR PRADESH      1
6                     RAJASTHAN      0
7                    PUDUCHERRY      0
8                    CHANDIGARH      0
9                       MIZORAM      0
10                   TAMIL NADU      0
11                  UTTARAKHAND      0
12                        ASSAM      0
13                  WEST BENGAL      0
14              JAMMU & KASHMIR      0
15             HIMACHAL PRADESH      0
16                    MEGHALAYA      0
17                       SIKKIM      0
18               MADHYA PRADESH      0
19                    JHARKHAND      0
20                       KERALA      0
21       DADRA AND NAGAR HAVELI      0
22  ANDAMAN AND NICOBAR ISLANDS      0
23            JAMMU AND KASHMIR      0
24                 CHHATTISGARH      0
25                      MANIPUR      0
26                       ODISHA      0
27                  LAKSHADWEEP      0
28                DAMAN AND DIU      0
29                    TELANGANA      0
30                       PUNJAB      0
31                        BIHAR      0
32                     NAGALAND      0
33                      TRIPURA      0
34               ANDHRA PRADESH      0
35            ARUNACHAL PRADESH      0
36                  MAHARASHTRA      0

In [54]:
allstates = pd.read_csv("/home/harshit/geography/district.csv") 
allstates = allstates["State"]
for i in allstates:
    df=pd.DataFrame(columns=["Company"])
    for index, j in data.iterrows():
        if(i==j["HQ"]): 
            m= pd.DataFrame([[j["Security Name"]]],columns=["Company"])
            df=df.append(m,ignore_index=True)
    df.to_csv("/home/harshit/geography/hqportfolios/"+i+".csv",index=False)

0                      WEST BENGAL
1                        TELANGANA
2                   MADHYA PRADESH
3                    UTTAR PRADESH
4                          GUJARAT
5                      MAHARASHTRA
6                          MIZORAM
7                        RAJASTHAN
8                      MAHARASHTRA
9                           KERALA
10                   UTTAR PRADESH
11                     WEST BENGAL
12                  MADHYA PRADESH
13                   UTTAR PRADESH
14                     UTTARAKHAND
15                       RAJASTHAN
16                         HARYANA
17                   UTTAR PRADESH
18                   UTTAR PRADESH
19                     MAHARASHTRA
20                         GUJARAT
21                          PUNJAB
22                   UTTAR PRADESH
23                         GUJARAT
24                  ANDHRA PRADESH
25               JAMMU AND KASHMIR
26     ANDAMAN AND NICOBAR ISLANDS
27               ARUNACHAL PRADESH
28                          ODISHA
29                  MADHYA PRADESH
                  ...
648                        TRIPURA
649                  UTTAR PRADESH
650                    UTTARAKHAND
651                        GUJARAT
652                          BIHAR
653                        GUJARAT
654                  UTTAR PRADESH
655                     TAMIL NADU
656                 MADHYA PRADESH
657                      KARNATAKA
658                      TELANGANA
659                     TAMIL NADU
660                     TAMIL NADU
661                 ANDHRA PRADESH
662                 ANDHRA PRADESH
663                      TELANGANA
664                      TELANGANA
665                      TELANGANA
666                    MAHARASHTRA
667                    MAHARASHTRA
668                         KERALA
669                        TRIPURA
670                       NAGALAND
671                 ANDHRA PRADESH
672                      TELANGANA
673                      KARNATAKA
674                        HARYANA
675                     PUDUCHERRY
676                    MAHARASHTRA
677                       NAGALAND
Name: State, Length: 678, dtype: object